### PR TITLE
Add smoketest that just loads the context to validate startup

### PR DESCRIPTION
**Pull request by Yolgie**

### CODE REVIEW

**Review by kadhonn — COMMENTED** [review]
do all other spring boot apps already have the same test?

**Comment by Yolgie** [comment]
@kadhonn i'm sorry, i don't understand what you are asking

**Comment by kadhonn** [comment]
we have more spring boot app. do all of them have the same tests or do some of them still need the same test?

**Comment by Yolgie** [comment]
ahh, you are a little to fast for me, added it to the first one for testing and currently adding it to all of them :)

**Pull request merged**
