### PR TITLE
a11y: monochrome manual testing

### LINKED ISSUE #413: A11Y: test HtmlPublisher against monochrome screens

### PR DESCRIPTION
**Pull request by mahdikhashan**
resolves #413 

TODO:
- manual visual test in a monochrome screen setup
- add user stories for people with such disabilities

### CODE REVIEW

**Comment by mahdikhashan** [comment]
- links should have underlines in monochrome setup

**Comment by mahdikhashan** [comment]
- different colors should have different shades to be distinguishable in monochrome setup

**Comment by mahdikhashan** [comment]
- textures and patterns can be used to improve the perceivability of colors in a monochrome setup

**Comment by mahdikhashan** [comment]
primary red color contrast compared to the image inside it often make it hard to distinguish the image from the background.

image
image

**Comment by mahdikhashan** [comment]
colorblind webpage test: 

1. protanopia (red-green color blindness - red cones)

url: https://www.toptal.com/designers/colorfilter?orig_uri=https://boudicca.events/&process_type=protan

image

2. deuteranopia (red-green color blindness - green cones)

url: https://www.toptal.com/designers/colorfilter?orig_uri=https://boudicca.events/&process_type=deutan

image

3. tritanopia (blue-yellow color blindness)

url: https://www.toptal.com/designers/colorfilter/

image

4. greyscale

url: https://www.toptal.com/designers/colorfilter?orig_uri=https://boudicca.events/&process_type=grey

image

**Comment by mahdikhashan** [comment]
### Test Report:

despite the fact this PR was supposed to only address the HtmlPublisher against a monochrome screen test setup, I used this opportunity to fully test the "Use of Color" w.r.t [understanding success criterion 1.4.1](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color.html#adaptable) rule of WCAG.

#### Tools

1. High Contrast Chrome plugin ([link](https://chromewebstore.google.com/detail/high-contrast/djcfdncoelnlbldjfhinnjlhdjlikmph)) 
2. Total Colorfilter ([link](http://www.toptal.com/designers/colorfilter/))

#### Test Environment

Chrome 123.x - official build - arm64
macOS Monterey 12.5.1

#### Test Success Criterions 

- Users with partial sight often experience limited color vision.
- Some older users may not be able to see color well.
- Users who have color-blindness benefit when information conveyed by color is available in other visual ways.
- People using limited color monochrome displays may be unable to access color-dependent information.
- Users who have problems distinguishing between colors can look or listen for text cues.

#### Test Result

After conducting the grayscale and colorblind test on the attached images, it is evident that the colors used for categorization do not effectively convey information for individuals with color vision disabilities. The reliance on color as the sole means of distinguishing categories poses a significant barrier to users who may have difficulty perceiving certain colors. This finding highlights the importance of implementing alternative visual cues or methods to ensure accessibility for all users, particularly those with color vision impairments.

**Review by kadhonn — APPROVED** [review]

**Pull request merged**
