### PR TITLE
Add GPL3 to project (approve needed by all current contributors)

### PR DESCRIPTION
**Pull request by Yolgie**
Dear @kadhonn @p4dd9 @twatzl @cstenglein @belehla 

Please add a comment with: 
   `Co-authored-by: name <name@example.com>` 
to approve the added licence for the whole repository including your contributions. I will then ammend the commit message on merge to add all coauthorships to the commit.

### CODE REVIEW

**Comment by kadhonn** [comment]
Co-authored-by: abl <ableimat@gmx.at>

**Comment by p4dd9** [comment]
Co-authored-by: pat pat.obermueller@gmail.com

**Comment by cstenglein** [comment]
Co-authored-by: cstenglein <christoph@cstenglein.com>

**Comment by belehla** [comment]
Co-authored-by: belehla bernadette@hammerle.me

**Comment by twatzl** [comment]
Co-authored-by: twatzl [twatzl@gmx.at](mailto:twatzl@gmx.at)

**Pull request merged**
