### PR TITLE
Add event collector for fhLUG events

### PR DESCRIPTION
**Pull request by knittl**
Adapted from the ValugCollector.

Completely untested, let me know if anything is missing. Happy for pointers how to test :)

### CODE REVIEW

**Review by kadhonn — COMMENTED** [review]
hey, thank you for contributing a new event collector!
code looks good to me, but please test and add it to the two runner classes as described in our doc: https://github.com/boudicca-events/boudicca.events/blob/main/docs/tech/EVENTCOLLECTORS.md#developing-your-own-collector

**Comment by knittl** [comment]
Thanks for the help and the link! I added the collector now locally and adapted/fixed the code (date errored with date-only events, event URLs weren't added)

**Review by kadhonn — APPROVED** [review]
looks great to me, thanks for creating a collector!

do you maybe have any feedback for our docs, or how hard it was for you to write the collector?

**Comment by knittl** [comment]
@kadhonn A copy-pasted the collector from another ical based collector, so it was simple enough. Docs were helpful and straightforward, once I found them :) The blame is on me for not looking better for them before opening the PR.

**Pull request merged**
